=== ammon-m/3d-renderer-js/src/assets/models/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "model schema",
  "type": "object",
  "properties": {
    "v": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "number"
        }
      }
    },
    "vt": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "number"
        }
      }
    },
    "vn": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "number"
        }
      }
    },
    "f": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    }
  },
  "required": [
    "v",
    "vt",
    "vn",
    "f"
  ]
}

=== ammon-m/3d-renderer-js/src/assets/models/cube.json
{
    "v": [
        [-0.5, -0.5, -0.5 ],
        [-0.5,  0.5, -0.5 ],
        [ 0.5,  0.5, -0.5 ],
        [ 0.5, -0.5, -0.5 ],
        [-0.5, -0.5,  0.5 ],
        [-0.5,  0.5,  0.5 ],
        [ 0.5,  0.5,  0.5 ],
        [ 0.5, -0.5,  0.5 ]
    ],
    "vt": [
        [ 0.25, 1.00 ],
        [ 0.50, 1.00 ],
        [ 0,    0.75 ],
        [ 0.25, 0.75 ],
        [ 0.50, 0.75 ],
        [ 0.75, 0.75 ],
        [ 0,    0.50 ],
        [ 0.25, 0.50 ],
        [ 0.50, 0.50 ],
        [ 0.75, 0.50 ],
        [ 0.25, 0.25 ],
        [ 0.50, 0.25 ],
        [ 0.25, 0    ],
        [ 0.50, 0    ]
    ],
    "vn": [
        [ 1.0,  0.0,  0.0 ],
        [-1.0,  0.0,  0.0 ],
        [ 0.0,  1.0,  0.0 ],
        [ 0.0, -1.0,  0.0 ],
        [ 0.0,  0.0,  1.0 ],
        [ 0.0,  0.0, -1.0 ]
    ],
    "f": [
        ["3/10/1", "7/6/1", "8/5/1"],
        ["3/10/1", "8/5/1", "4/9/1"],

        ["1/8/2", "5/4/2", "6/3/2"],
        ["1/8/2", "6/3/2", "2/7/2"],

        ["7/14/3", "3/12/3", "2/11/3"],
        ["7/14/3", "2/11/3", "6/13/3"],

        ["4/9/4", "8/5/4", "5/4/4"],
        ["4/9/4", "5/4/4", "1/8/4"],

        ["8/5/5", "7/2/5", "6/1/5"],
        ["8/5/5", "6/1/5", "5/4/5"],

        ["3/12/6", "4/9/6", "1/8/6"],
        ["3/12/6", "1/8/6", "2/11/6"]
    ]
}
